# Generated by Django 4.1.11 on 2023-09-15 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=200)),
                ('Client_Email', models.CharField(max_length=200, unique=True)),
                ('Client_Phone_Number', models.CharField(max_length=40)),
                ('Client_Password', models.CharField(max_length=200)),
                ('Client_Address', models.CharField(max_length=200)),
                ('Client_Description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Client_Table',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('Project_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=200)),
                ('Project_Description', models.CharField(max_length=500)),
                ('Project_Start_Date', models.DateField(default=datetime.datetime.today)),
                ('Project_End_Date', models.DateField(default=datetime.datetime.today)),
                ('Project_Status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('Project_Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Client_Id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='Issuemanage.client')),
            ],
            options={
                'db_table': 'Projects_Table',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('Task_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=200)),
                ('Task_Description', models.CharField(max_length=500)),
                ('Task_Start_Date', models.DateField(default=datetime.datetime.today)),
                ('Task_End_Date', models.DateField(default=datetime.datetime.today)),
                ('Task_Status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('Task_Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Project_Id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='Issuemanage.projects')),
            ],
            options={
                'db_table': 'Tasks_Table',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('Issue_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_Name', models.CharField(max_length=200)),
                ('Issue_Raised_By', models.CharField(max_length=200)),
                ('Issue_Assigned_To', models.CharField(max_length=200)),
                ('Issue_Description', models.CharField(max_length=500)),
                ('Issue_Date', models.DateField(auto_now=True)),
                ('Issue_Status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('Issue_Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Task_Id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='Issuemanage.tasks')),
            ],
            options={
                'db_table': 'Issues_Table',
            },
        ),
    ]
